In [2]:
import pandas as pd
import numpy as np

In [4]:

books = pd.read_csv('processed datasets/Books.csv')
ratings = pd.read_csv('processed datasets/Ratings.csv')

In [5]:
merged_data = pd.merge(ratings, books, on='ISBN')
merged_data.head()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002-01-01,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,276726,0155061224,5,Rites of Passage,Judith Rae,2001-01-01,Heinle,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...
2,276727,0446520802,0,The Notebook,Nicholas Sparks,1996-01-01,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
3,276729,052165615X,3,Help!: Level 1,Philip Prowse,1999-01-01,Cambridge University Press,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...
4,276729,0521795028,6,The Amsterdam Connection : Level 4 (Cambridge ...,Sue Leather,2001-01-01,Cambridge University Press,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...

In [7]:
merged_data = merged_data.iloc[: , : 7 ]

##### a book that has been rated 10 highest number of times

In [ ]:
#highest ratins
top_rating = merged_data['Book-Rating'].max()


#book ibn with highest number of 10star ratings
most_rated_books = merged_data[merged_data['Book-Rating'] == top_rating]['ISBN'].value_counts()[:10].index
most_rated_books


top_books = books[books['ISBN'].isin(most_rated_books)]
top_books.iloc[: ,:5]

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher
37,0446310786,To Kill a Mockingbird,Harper Lee,1988-01-01,Little Brown &amp; Company
356,0142001740,The Secret Life of Bees,Sue Monk Kidd,2003-01-01,Penguin Books
408,0316666343,The Lovely Bones: A Novel,Alice Sebold,2002-01-01,"Little, Brown"
522,0312195516,The Red Tent (Bestselling Backlist),Anita Diamant,1998-01-01,Picador USA
748,0385504209,The Da Vinci Code,Dan Brown,2003-01-01,Doubleday
2143,059035342X,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,1999-01-01,Arthur A. Levine Books
2290,0385484518,"Tuesdays with Morrie: An Old Man, a Young Man,...",MITCH ALBOM,1997-01-01,Doubleday
3839,0439136350,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,1999-01-01,Scholastic
5431,0439139597,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,2000-01-01,Scholastic
5506,043935806X,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,2003-01-01,Scholastic

#### customised ratings based suggesttion 
-- > (user gives "number of stars" as input then get suggestion wrt ot it)

In [45]:
ratings = int(input('Enter ratings : '))


#book ibn with highest number of 10star ratings
most_rated_books = merged_data[merged_data['Book-Rating'] == ratings]['ISBN'].value_counts()[:10].index
most_rated_books


top_books = books[books['ISBN'].isin(most_rated_books)]
top_books.iloc[: ,:5]

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher
26,0971880107,Wild Animus,Rich Shapero,2004-01-01,Too Far
231,0452282152,Girl with a Pearl Earring,Tracy Chevalier,2001-01-01,Plume Books
305,044023722X,A Painted House,John Grisham,2001-01-01,Dell Publishing Company
408,0316666343,The Lovely Bones: A Novel,Alice Sebold,2002-01-01,"Little, Brown"
522,0312195516,The Red Tent (Bestselling Backlist),Anita Diamant,1998-01-01,Picador USA
748,0385504209,The Da Vinci Code,Dan Brown,2003-01-01,Doubleday
1105,0060928336,Divine Secrets of the Ya-Ya Sisterhood: A Novel,Rebecca Wells,1997-01-01,Perennial
1680,0440226430,Summer Sisters,Judy Blume,1999-01-01,Dell Publishing Company
2526,0345337662,Interview with the Vampire,Anne Rice,1993-01-01,Ballantine Books
4824,0316601950,The Pilot's Wife : A Novel,Anita Shreve,1999-01-01,Back Bay Books